# SERVER
server.port=8080

# DATABASE (SQL SERVER)
# Chuỗi kết nối tới database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA & HIBERNATE
# Dùng 'validate' để Spring Boot kiểm tra entity khớp với DB
spring.jpa.hibernate.ddl-auto=validate
# Hiển thị và format câu lệnh SQL trên console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Notifications (MAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT secret key
jwt.secret=VmVyeVNlY3JldEtleUZvckxpYnJhcnlNYW5hZ2VtZW50U3lzdGVtQDIwMjQhQCMk
# Thời gian sống của token (s)
jwt.expiration=86400000